package com.webmiddle.circulocorp.protocol.protos;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PeriodicPositionProto.proto
public final class PeriodicPositionProto {

    private PeriodicPositionProto() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface PeriodicPositionOrBuilder extends
            // @@protoc_insertion_point(interface_extends:PeriodicPosition)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>required .EventHeader header = 1;</code>
         *
         * @return Whether the header field is set.
         */
        boolean hasHeader();

        /**
         * <code>required .EventHeader header = 1;</code>
         *
         * @return The header.
         */
        EventHeaderProto.EventHeader getHeader();

        /**
         * <code>required .EventHeader header = 1;</code>
         */
        EventHeaderProto.EventHeaderOrBuilder getHeaderOrBuilder();

        /**
         * <pre>
         * Engine revolutions per minute (r/min). Precision: 100
         * </pre>
         *
         * <code>optional uint32 rpm = 2;</code>
         *
         * @return Whether the rpm field is set.
         */
        boolean hasRpm();

        /**
         * <pre>
         * Engine revolutions per minute (r/min). Precision: 100
         * </pre>
         *
         * <code>optional uint32 rpm = 2;</code>
         *
         * @return The rpm.
         */
        int getRpm();

        /**
         * <pre>
         * Trip duration in seconds
         * </pre>
         *
         * <code>optional uint32 trip_duration_seconds = 3;</code>
         *
         * @return Whether the tripDurationSeconds field is set.
         */
        boolean hasTripDurationSeconds();

        /**
         * <pre>
         * Trip duration in seconds
         * </pre>
         *
         * <code>optional uint32 trip_duration_seconds = 3;</code>
         *
         * @return The tripDurationSeconds.
         */
        int getTripDurationSeconds();

        /**
         * <pre>
         * Trip distance in meters
         * </pre>
         *
         * <code>optional uint32 trip_distance_meters = 4;</code>
         *
         * @return Whether the tripDistanceMeters field is set.
         */
        boolean hasTripDistanceMeters();

        /**
         * <pre>
         * Trip distance in meters
         * </pre>
         *
         * <code>optional uint32 trip_distance_meters = 4;</code>
         *
         * @return The tripDistanceMeters.
         */
        int getTripDistanceMeters();
    }

    /**
     * <pre>
     * Periodic Position
     * </pre>
     *
     * Protobuf type {@code PeriodicPosition}
     */
    public static final class PeriodicPosition extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:PeriodicPosition)
            PeriodicPositionOrBuilder {

        private static final long serialVersionUID = 0L;
        // Use PeriodicPosition.newBuilder() to construct.

        private PeriodicPosition(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private PeriodicPosition() {
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new PeriodicPosition();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
                getUnknownFields() {
            return this.unknownFields;
        }

        private PeriodicPosition(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields
                    = com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            EventHeaderProto.EventHeader.Builder subBuilder = null;
                            if (((bitField0_ & 0x00000001) != 0)) {
                                subBuilder = header_.toBuilder();
                            }
                            header_ = input.readMessage(EventHeaderProto.EventHeader.PARSER, extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(header_);
                                header_ = subBuilder.buildPartial();
                            }
                            bitField0_ |= 0x00000001;
                            break;
                        }
                        case 16: {
                            bitField0_ |= 0x00000002;
                            rpm_ = input.readUInt32();
                            break;
                        }
                        case 24: {
                            bitField0_ |= 0x00000004;
                            tripDurationSeconds_ = input.readUInt32();
                            break;
                        }
                        case 32: {
                            bitField0_ |= 0x00000008;
                            tripDistanceMeters_ = input.readUInt32();
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
                getDescriptor() {
            return PeriodicPositionProto.internal_static_PeriodicPosition_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
                internalGetFieldAccessorTable() {
            return PeriodicPositionProto.internal_static_PeriodicPosition_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            PeriodicPositionProto.PeriodicPosition.class, PeriodicPositionProto.PeriodicPosition.Builder.class);
        }

        private int bitField0_;
        public static final int HEADER_FIELD_NUMBER = 1;
        private EventHeaderProto.EventHeader header_;

        /**
         * <code>required .EventHeader header = 1;</code>
         *
         * @return Whether the header field is set.
         */
        @java.lang.Override
        public boolean hasHeader() {
            return ((bitField0_ & 0x00000001) != 0);
        }

        /**
         * <code>required .EventHeader header = 1;</code>
         *
         * @return The header.
         */
        @java.lang.Override
        public EventHeaderProto.EventHeader getHeader() {
            return header_ == null ? EventHeaderProto.EventHeader.getDefaultInstance() : header_;
        }

        /**
         * <code>required .EventHeader header = 1;</code>
         */
        @java.lang.Override
        public EventHeaderProto.EventHeaderOrBuilder getHeaderOrBuilder() {
            return header_ == null ? EventHeaderProto.EventHeader.getDefaultInstance() : header_;
        }

        public static final int RPM_FIELD_NUMBER = 2;
        private int rpm_;

        /**
         * <pre>
         * Engine revolutions per minute (r/min). Precision: 100
         * </pre>
         *
         * <code>optional uint32 rpm = 2;</code>
         *
         * @return Whether the rpm field is set.
         */
        @java.lang.Override
        public boolean hasRpm() {
            return ((bitField0_ & 0x00000002) != 0);
        }

        /**
         * <pre>
         * Engine revolutions per minute (r/min). Precision: 100
         * </pre>
         *
         * <code>optional uint32 rpm = 2;</code>
         *
         * @return The rpm.
         */
        @java.lang.Override
        public int getRpm() {
            return rpm_;
        }

        public static final int TRIP_DURATION_SECONDS_FIELD_NUMBER = 3;
        private int tripDurationSeconds_;

        /**
         * <pre>
         * Trip duration in seconds
         * </pre>
         *
         * <code>optional uint32 trip_duration_seconds = 3;</code>
         *
         * @return Whether the tripDurationSeconds field is set.
         */
        @java.lang.Override
        public boolean hasTripDurationSeconds() {
            return ((bitField0_ & 0x00000004) != 0);
        }

        /**
         * <pre>
         * Trip duration in seconds
         * </pre>
         *
         * <code>optional uint32 trip_duration_seconds = 3;</code>
         *
         * @return The tripDurationSeconds.
         */
        @java.lang.Override
        public int getTripDurationSeconds() {
            return tripDurationSeconds_;
        }

        public static final int TRIP_DISTANCE_METERS_FIELD_NUMBER = 4;
        private int tripDistanceMeters_;

        /**
         * <pre>
         * Trip distance in meters
         * </pre>
         *
         * <code>optional uint32 trip_distance_meters = 4;</code>
         *
         * @return Whether the tripDistanceMeters field is set.
         */
        @java.lang.Override
        public boolean hasTripDistanceMeters() {
            return ((bitField0_ & 0x00000008) != 0);
        }

        /**
         * <pre>
         * Trip distance in meters
         * </pre>
         *
         * <code>optional uint32 trip_distance_meters = 4;</code>
         *
         * @return The tripDistanceMeters.
         */
        @java.lang.Override
        public int getTripDistanceMeters() {
            return tripDistanceMeters_;
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) {
                return true;
            }
            if (isInitialized == 0) {
                return false;
            }

            if (!hasHeader()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!getHeader().isInitialized()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (((bitField0_ & 0x00000001) != 0)) {
                output.writeMessage(1, getHeader());
            }
            if (((bitField0_ & 0x00000002) != 0)) {
                output.writeUInt32(2, rpm_);
            }
            if (((bitField0_ & 0x00000004) != 0)) {
                output.writeUInt32(3, tripDurationSeconds_);
            }
            if (((bitField0_ & 0x00000008) != 0)) {
                output.writeUInt32(4, tripDistanceMeters_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) {
                return size;
            }

            size = 0;
            if (((bitField0_ & 0x00000001) != 0)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(1, getHeader());
            }
            if (((bitField0_ & 0x00000002) != 0)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(2, rpm_);
            }
            if (((bitField0_ & 0x00000004) != 0)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(3, tripDurationSeconds_);
            }
            if (((bitField0_ & 0x00000008) != 0)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(4, tripDistanceMeters_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof PeriodicPositionProto.PeriodicPosition)) {
                return super.equals(obj);
            }
            PeriodicPositionProto.PeriodicPosition other = (PeriodicPositionProto.PeriodicPosition) obj;

            if (hasHeader() != other.hasHeader()) {
                return false;
            }
            if (hasHeader()) {
                if (!getHeader()
                        .equals(other.getHeader())) {
                    return false;
                }
            }
            if (hasRpm() != other.hasRpm()) {
                return false;
            }
            if (hasRpm()) {
                if (getRpm()
                        != other.getRpm()) {
                    return false;
                }
            }
            if (hasTripDurationSeconds() != other.hasTripDurationSeconds()) {
                return false;
            }
            if (hasTripDurationSeconds()) {
                if (getTripDurationSeconds()
                        != other.getTripDurationSeconds()) {
                    return false;
                }
            }
            if (hasTripDistanceMeters() != other.hasTripDistanceMeters()) {
                return false;
            }
            if (hasTripDistanceMeters()) {
                if (getTripDistanceMeters()
                        != other.getTripDistanceMeters()) {
                    return false;
                }
            }
            if (!unknownFields.equals(other.unknownFields)) {
                return false;
            }
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasHeader()) {
                hash = (37 * hash) + HEADER_FIELD_NUMBER;
                hash = (53 * hash) + getHeader().hashCode();
            }
            if (hasRpm()) {
                hash = (37 * hash) + RPM_FIELD_NUMBER;
                hash = (53 * hash) + getRpm();
            }
            if (hasTripDurationSeconds()) {
                hash = (37 * hash) + TRIP_DURATION_SECONDS_FIELD_NUMBER;
                hash = (53 * hash) + getTripDurationSeconds();
            }
            if (hasTripDistanceMeters()) {
                hash = (37 * hash) + TRIP_DISTANCE_METERS_FIELD_NUMBER;
                hash = (53 * hash) + getTripDistanceMeters();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static PeriodicPositionProto.PeriodicPosition parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static PeriodicPositionProto.PeriodicPosition parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static PeriodicPositionProto.PeriodicPosition parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static PeriodicPositionProto.PeriodicPosition parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static PeriodicPositionProto.PeriodicPosition parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static PeriodicPositionProto.PeriodicPosition parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static PeriodicPositionProto.PeriodicPosition parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static PeriodicPositionProto.PeriodicPosition parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static PeriodicPositionProto.PeriodicPosition parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static PeriodicPositionProto.PeriodicPosition parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static PeriodicPositionProto.PeriodicPosition parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static PeriodicPositionProto.PeriodicPosition parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(PeriodicPositionProto.PeriodicPosition prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * <pre>
         * Periodic Position
         * </pre>
         *
         * Protobuf type {@code PeriodicPosition}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:PeriodicPosition)
                PeriodicPositionProto.PeriodicPositionOrBuilder {

            public static final com.google.protobuf.Descriptors.Descriptor
                    getDescriptor() {
                return PeriodicPositionProto.internal_static_PeriodicPosition_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
                    internalGetFieldAccessorTable() {
                return PeriodicPositionProto.internal_static_PeriodicPosition_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                PeriodicPositionProto.PeriodicPosition.class, PeriodicPositionProto.PeriodicPosition.Builder.class);
            }

            // Construct using PeriodicPositionProto.PeriodicPosition.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
                    getHeaderFieldBuilder();
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                if (headerBuilder_ == null) {
                    header_ = null;
                } else {
                    headerBuilder_.clear();
                }
                bitField0_ = (bitField0_ & ~0x00000001);
                rpm_ = 0;
                bitField0_ = (bitField0_ & ~0x00000002);
                tripDurationSeconds_ = 0;
                bitField0_ = (bitField0_ & ~0x00000004);
                tripDistanceMeters_ = 0;
                bitField0_ = (bitField0_ & ~0x00000008);
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
                    getDescriptorForType() {
                return PeriodicPositionProto.internal_static_PeriodicPosition_descriptor;
            }

            @java.lang.Override
            public PeriodicPositionProto.PeriodicPosition getDefaultInstanceForType() {
                return PeriodicPositionProto.PeriodicPosition.getDefaultInstance();
            }

            @java.lang.Override
            public PeriodicPositionProto.PeriodicPosition build() {
                PeriodicPositionProto.PeriodicPosition result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public PeriodicPositionProto.PeriodicPosition buildPartial() {
                PeriodicPositionProto.PeriodicPosition result = new PeriodicPositionProto.PeriodicPosition(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    if (headerBuilder_ == null) {
                        result.header_ = header_;
                    } else {
                        result.header_ = headerBuilder_.build();
                    }
                    to_bitField0_ |= 0x00000001;
                }
                if (((from_bitField0_ & 0x00000002) != 0)) {
                    result.rpm_ = rpm_;
                    to_bitField0_ |= 0x00000002;
                }
                if (((from_bitField0_ & 0x00000004) != 0)) {
                    result.tripDurationSeconds_ = tripDurationSeconds_;
                    to_bitField0_ |= 0x00000004;
                }
                if (((from_bitField0_ & 0x00000008) != 0)) {
                    result.tripDistanceMeters_ = tripDistanceMeters_;
                    to_bitField0_ |= 0x00000008;
                }
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof PeriodicPositionProto.PeriodicPosition) {
                    return mergeFrom((PeriodicPositionProto.PeriodicPosition) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(PeriodicPositionProto.PeriodicPosition other) {
                if (other == PeriodicPositionProto.PeriodicPosition.getDefaultInstance()) {
                    return this;
                }
                if (other.hasHeader()) {
                    mergeHeader(other.getHeader());
                }
                if (other.hasRpm()) {
                    setRpm(other.getRpm());
                }
                if (other.hasTripDurationSeconds()) {
                    setTripDurationSeconds(other.getTripDurationSeconds());
                }
                if (other.hasTripDistanceMeters()) {
                    setTripDistanceMeters(other.getTripDistanceMeters());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                if (!hasHeader()) {
                    return false;
                }
                if (!getHeader().isInitialized()) {
                    return false;
                }
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                PeriodicPositionProto.PeriodicPosition parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (PeriodicPositionProto.PeriodicPosition) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }
            private int bitField0_;

            private EventHeaderProto.EventHeader header_;
            private com.google.protobuf.SingleFieldBuilderV3<
          EventHeaderProto.EventHeader, EventHeaderProto.EventHeader.Builder, EventHeaderProto.EventHeaderOrBuilder> headerBuilder_;

            /**
             * <code>required .EventHeader header = 1;</code>
             *
             * @return Whether the header field is set.
             */
            public boolean hasHeader() {
                return ((bitField0_ & 0x00000001) != 0);
            }

            /**
             * <code>required .EventHeader header = 1;</code>
             *
             * @return The header.
             */
            public EventHeaderProto.EventHeader getHeader() {
                if (headerBuilder_ == null) {
                    return header_ == null ? EventHeaderProto.EventHeader.getDefaultInstance() : header_;
                } else {
                    return headerBuilder_.getMessage();
                }
            }

            /**
             * <code>required .EventHeader header = 1;</code>
             */
            public Builder setHeader(EventHeaderProto.EventHeader value) {
                if (headerBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    header_ = value;
                    onChanged();
                } else {
                    headerBuilder_.setMessage(value);
                }
                bitField0_ |= 0x00000001;
                return this;
            }

            /**
             * <code>required .EventHeader header = 1;</code>
             */
            public Builder setHeader(
                    EventHeaderProto.EventHeader.Builder builderForValue) {
                if (headerBuilder_ == null) {
                    header_ = builderForValue.build();
                    onChanged();
                } else {
                    headerBuilder_.setMessage(builderForValue.build());
                }
                bitField0_ |= 0x00000001;
                return this;
            }

            /**
             * <code>required .EventHeader header = 1;</code>
             */
            public Builder mergeHeader(EventHeaderProto.EventHeader value) {
                if (headerBuilder_ == null) {
                    if (((bitField0_ & 0x00000001) != 0)
                            && header_ != null
                            && header_ != EventHeaderProto.EventHeader.getDefaultInstance()) {
                        header_
                                = EventHeaderProto.EventHeader.newBuilder(header_).mergeFrom(value).buildPartial();
                    } else {
                        header_ = value;
                    }
                    onChanged();
                } else {
                    headerBuilder_.mergeFrom(value);
                }
                bitField0_ |= 0x00000001;
                return this;
            }

            /**
             * <code>required .EventHeader header = 1;</code>
             */
            public Builder clearHeader() {
                if (headerBuilder_ == null) {
                    header_ = null;
                    onChanged();
                } else {
                    headerBuilder_.clear();
                }
                bitField0_ = (bitField0_ & ~0x00000001);
                return this;
            }

            /**
             * <code>required .EventHeader header = 1;</code>
             */
            public EventHeaderProto.EventHeader.Builder getHeaderBuilder() {
                bitField0_ |= 0x00000001;
                onChanged();
                return getHeaderFieldBuilder().getBuilder();
            }

            /**
             * <code>required .EventHeader header = 1;</code>
             */
            public EventHeaderProto.EventHeaderOrBuilder getHeaderOrBuilder() {
                if (headerBuilder_ != null) {
                    return headerBuilder_.getMessageOrBuilder();
                } else {
                    return header_ == null
                            ? EventHeaderProto.EventHeader.getDefaultInstance() : header_;
                }
            }

            /**
             * <code>required .EventHeader header = 1;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
          EventHeaderProto.EventHeader, EventHeaderProto.EventHeader.Builder, EventHeaderProto.EventHeaderOrBuilder>
                    getHeaderFieldBuilder() {
                if (headerBuilder_ == null) {
                    headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              EventHeaderProto.EventHeader, EventHeaderProto.EventHeader.Builder, EventHeaderProto.EventHeaderOrBuilder>(
                            getHeader(),
                            getParentForChildren(),
                            isClean());
                    header_ = null;
                }
                return headerBuilder_;
            }

            private int rpm_;

            /**
             * <pre>
             * Engine revolutions per minute (r/min). Precision: 100
             * </pre>
             *
             * <code>optional uint32 rpm = 2;</code>
             *
             * @return Whether the rpm field is set.
             */
            @java.lang.Override
            public boolean hasRpm() {
                return ((bitField0_ & 0x00000002) != 0);
            }

            /**
             * <pre>
             * Engine revolutions per minute (r/min). Precision: 100
             * </pre>
             *
             * <code>optional uint32 rpm = 2;</code>
             *
             * @return The rpm.
             */
            @java.lang.Override
            public int getRpm() {
                return rpm_;
            }

            /**
             * <pre>
             * Engine revolutions per minute (r/min). Precision: 100
             * </pre>
             *
             * <code>optional uint32 rpm = 2;</code>
             *
             * @param value The rpm to set.
             * @return This builder for chaining.
             */
            public Builder setRpm(int value) {
                bitField0_ |= 0x00000002;
                rpm_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * Engine revolutions per minute (r/min). Precision: 100
             * </pre>
             *
             * <code>optional uint32 rpm = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearRpm() {
                bitField0_ = (bitField0_ & ~0x00000002);
                rpm_ = 0;
                onChanged();
                return this;
            }

            private int tripDurationSeconds_;

            /**
             * <pre>
             * Trip duration in seconds
             * </pre>
             *
             * <code>optional uint32 trip_duration_seconds = 3;</code>
             *
             * @return Whether the tripDurationSeconds field is set.
             */
            @java.lang.Override
            public boolean hasTripDurationSeconds() {
                return ((bitField0_ & 0x00000004) != 0);
            }

            /**
             * <pre>
             * Trip duration in seconds
             * </pre>
             *
             * <code>optional uint32 trip_duration_seconds = 3;</code>
             *
             * @return The tripDurationSeconds.
             */
            @java.lang.Override
            public int getTripDurationSeconds() {
                return tripDurationSeconds_;
            }

            /**
             * <pre>
             * Trip duration in seconds
             * </pre>
             *
             * <code>optional uint32 trip_duration_seconds = 3;</code>
             *
             * @param value The tripDurationSeconds to set.
             * @return This builder for chaining.
             */
            public Builder setTripDurationSeconds(int value) {
                bitField0_ |= 0x00000004;
                tripDurationSeconds_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * Trip duration in seconds
             * </pre>
             *
             * <code>optional uint32 trip_duration_seconds = 3;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearTripDurationSeconds() {
                bitField0_ = (bitField0_ & ~0x00000004);
                tripDurationSeconds_ = 0;
                onChanged();
                return this;
            }

            private int tripDistanceMeters_;

            /**
             * <pre>
             * Trip distance in meters
             * </pre>
             *
             * <code>optional uint32 trip_distance_meters = 4;</code>
             *
             * @return Whether the tripDistanceMeters field is set.
             */
            @java.lang.Override
            public boolean hasTripDistanceMeters() {
                return ((bitField0_ & 0x00000008) != 0);
            }

            /**
             * <pre>
             * Trip distance in meters
             * </pre>
             *
             * <code>optional uint32 trip_distance_meters = 4;</code>
             *
             * @return The tripDistanceMeters.
             */
            @java.lang.Override
            public int getTripDistanceMeters() {
                return tripDistanceMeters_;
            }

            /**
             * <pre>
             * Trip distance in meters
             * </pre>
             *
             * <code>optional uint32 trip_distance_meters = 4;</code>
             *
             * @param value The tripDistanceMeters to set.
             * @return This builder for chaining.
             */
            public Builder setTripDistanceMeters(int value) {
                bitField0_ |= 0x00000008;
                tripDistanceMeters_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * Trip distance in meters
             * </pre>
             *
             * <code>optional uint32 trip_distance_meters = 4;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearTripDistanceMeters() {
                bitField0_ = (bitField0_ & ~0x00000008);
                tripDistanceMeters_ = 0;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }

            // @@protoc_insertion_point(builder_scope:PeriodicPosition)
        }

        // @@protoc_insertion_point(class_scope:PeriodicPosition)
        private static final PeriodicPositionProto.PeriodicPosition DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new PeriodicPositionProto.PeriodicPosition();
        }

        public static PeriodicPositionProto.PeriodicPosition getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        @java.lang.Deprecated
        public static final com.google.protobuf.Parser<PeriodicPosition> PARSER = new com.google.protobuf.AbstractParser<PeriodicPosition>() {
            @java.lang.Override
            public PeriodicPosition parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new PeriodicPosition(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<PeriodicPosition> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<PeriodicPosition> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public PeriodicPositionProto.PeriodicPosition getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor internal_static_PeriodicPosition_descriptor;
    private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_PeriodicPosition_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
            getDescriptor() {
        return descriptor;
    }
    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

    static {
        java.lang.String[] descriptorData = {
            "\n\033PeriodicPositionProto.proto\032\026EventHead"
            + "erProto.proto\"z\n\020PeriodicPosition\022\034\n\006hea"
            + "der\030\001 \002(\0132\014.EventHeader\022\013\n\003rpm\030\002 \001(\r\022\035\n\025"
            + "trip_duration_seconds\030\003 \001(\r\022\034\n\024trip_dist"
            + "ance_meters\030\004 \001(\r"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                            EventHeaderProto.getDescriptor(),});
        internal_static_PeriodicPosition_descriptor
                = getDescriptor().getMessageTypes().get(0);
        internal_static_PeriodicPosition_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_PeriodicPosition_descriptor,
                new java.lang.String[]{"Header", "Rpm", "TripDurationSeconds", "TripDistanceMeters",});
        EventHeaderProto.getDescriptor();
    }

    // @@protoc_insertion_point(outer_class_scope)
}
