// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto
package others;

public final class MessageProtos {

    private MessageProtos() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface DataOrBuilder extends
            // @@protoc_insertion_point(interface_extends:com.webmiddle.circulocorp.protocol.Data)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional string vin = 1;</code>
         *
         * @return Whether the vin field is set.
         */
        boolean hasVin();

        /**
         * <code>optional string vin = 1;</code>
         *
         * @return The vin.
         */
        java.lang.String getVin();

        /**
         * <code>optional string vin = 1;</code>
         *
         * @return The bytes for vin.
         */
        com.google.protobuf.ByteString
                getVinBytes();

        /**
         * <code>required string longitude = 2;</code>
         *
         * @return Whether the longitude field is set.
         */
        boolean hasLongitude();

        /**
         * <code>required string longitude = 2;</code>
         *
         * @return The longitude.
         */
        java.lang.String getLongitude();

        /**
         * <code>required string longitude = 2;</code>
         *
         * @return The bytes for longitude.
         */
        com.google.protobuf.ByteString
                getLongitudeBytes();

        /**
         * <code>required string latitude = 3;</code>
         *
         * @return Whether the latitude field is set.
         */
        boolean hasLatitude();

        /**
         * <code>required string latitude = 3;</code>
         *
         * @return The latitude.
         */
        java.lang.String getLatitude();

        /**
         * <code>required string latitude = 3;</code>
         *
         * @return The bytes for latitude.
         */
        com.google.protobuf.ByteString
                getLatitudeBytes();

        /**
         * <code>optional string utcTimestamp = 4;</code>
         *
         * @return Whether the utcTimestamp field is set.
         */
        boolean hasUtcTimestamp();

        /**
         * <code>optional string utcTimestamp = 4;</code>
         *
         * @return The utcTimestamp.
         */
        java.lang.String getUtcTimestamp();

        /**
         * <code>optional string utcTimestamp = 4;</code>
         *
         * @return The bytes for utcTimestamp.
         */
        com.google.protobuf.ByteString
                getUtcTimestampBytes();
    }

    /**
     * Protobuf type {@code com.webmiddle.circulocorp.protocol.Data}
     */
    public static final class Data extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:com.webmiddle.circulocorp.protocol.Data)
            DataOrBuilder {

        private static final long serialVersionUID = 0L;
        // Use Data.newBuilder() to construct.

        private Data(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private Data() {
            vin_ = "";
            longitude_ = "";
            latitude_ = "";
            utcTimestamp_ = "";
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new Data();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
                getUnknownFields() {
            return this.unknownFields;
        }

        private Data(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields
                    = com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000001;
                            vin_ = bs;
                            break;
                        }
                        case 18: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000002;
                            longitude_ = bs;
                            break;
                        }
                        case 26: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000004;
                            latitude_ = bs;
                            break;
                        }
                        case 34: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000008;
                            utcTimestamp_ = bs;
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
                getDescriptor() {
            return others.MessageProtos.internal_static_com_webmiddle_circulocorp_protocol_Data_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
                internalGetFieldAccessorTable() {
            return others.MessageProtos.internal_static_com_webmiddle_circulocorp_protocol_Data_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(others.MessageProtos.Data.class, others.MessageProtos.Data.Builder.class);
        }

        private int bitField0_;
        public static final int VIN_FIELD_NUMBER = 1;
        private volatile java.lang.Object vin_;

        /**
         * <code>optional string vin = 1;</code>
         *
         * @return Whether the vin field is set.
         */
        @java.lang.Override
        public boolean hasVin() {
            return ((bitField0_ & 0x00000001) != 0);
        }

        /**
         * <code>optional string vin = 1;</code>
         *
         * @return The vin.
         */
        @java.lang.Override
        public java.lang.String getVin() {
            java.lang.Object ref = vin_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs
                        = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    vin_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string vin = 1;</code>
         *
         * @return The bytes for vin.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
                getVinBytes() {
            java.lang.Object ref = vin_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b
                        = com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                vin_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int LONGITUDE_FIELD_NUMBER = 2;
        private volatile java.lang.Object longitude_;

        /**
         * <code>required string longitude = 2;</code>
         *
         * @return Whether the longitude field is set.
         */
        @java.lang.Override
        public boolean hasLongitude() {
            return ((bitField0_ & 0x00000002) != 0);
        }

        /**
         * <code>required string longitude = 2;</code>
         *
         * @return The longitude.
         */
        @java.lang.Override
        public java.lang.String getLongitude() {
            java.lang.Object ref = longitude_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs
                        = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    longitude_ = s;
                }
                return s;
            }
        }

        /**
         * <code>required string longitude = 2;</code>
         *
         * @return The bytes for longitude.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
                getLongitudeBytes() {
            java.lang.Object ref = longitude_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b
                        = com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                longitude_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int LATITUDE_FIELD_NUMBER = 3;
        private volatile java.lang.Object latitude_;

        /**
         * <code>required string latitude = 3;</code>
         *
         * @return Whether the latitude field is set.
         */
        @java.lang.Override
        public boolean hasLatitude() {
            return ((bitField0_ & 0x00000004) != 0);
        }

        /**
         * <code>required string latitude = 3;</code>
         *
         * @return The latitude.
         */
        @java.lang.Override
        public java.lang.String getLatitude() {
            java.lang.Object ref = latitude_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs
                        = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    latitude_ = s;
                }
                return s;
            }
        }

        /**
         * <code>required string latitude = 3;</code>
         *
         * @return The bytes for latitude.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
                getLatitudeBytes() {
            java.lang.Object ref = latitude_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b
                        = com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                latitude_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int UTCTIMESTAMP_FIELD_NUMBER = 4;
        private volatile java.lang.Object utcTimestamp_;

        /**
         * <code>optional string utcTimestamp = 4;</code>
         *
         * @return Whether the utcTimestamp field is set.
         */
        @java.lang.Override
        public boolean hasUtcTimestamp() {
            return ((bitField0_ & 0x00000008) != 0);
        }

        /**
         * <code>optional string utcTimestamp = 4;</code>
         *
         * @return The utcTimestamp.
         */
        @java.lang.Override
        public java.lang.String getUtcTimestamp() {
            java.lang.Object ref = utcTimestamp_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs
                        = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    utcTimestamp_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string utcTimestamp = 4;</code>
         *
         * @return The bytes for utcTimestamp.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
                getUtcTimestampBytes() {
            java.lang.Object ref = utcTimestamp_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b
                        = com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                utcTimestamp_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) {
                return true;
            }
            if (isInitialized == 0) {
                return false;
            }

            if (!hasLongitude()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasLatitude()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (((bitField0_ & 0x00000001) != 0)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, vin_);
            }
            if (((bitField0_ & 0x00000002) != 0)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, longitude_);
            }
            if (((bitField0_ & 0x00000004) != 0)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, latitude_);
            }
            if (((bitField0_ & 0x00000008) != 0)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 4, utcTimestamp_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) {
                return size;
            }

            size = 0;
            if (((bitField0_ & 0x00000001) != 0)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, vin_);
            }
            if (((bitField0_ & 0x00000002) != 0)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, longitude_);
            }
            if (((bitField0_ & 0x00000004) != 0)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, latitude_);
            }
            if (((bitField0_ & 0x00000008) != 0)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, utcTimestamp_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof others.MessageProtos.Data)) {
                return super.equals(obj);
            }
            others.MessageProtos.Data other = (others.MessageProtos.Data) obj;

            if (hasVin() != other.hasVin()) {
                return false;
            }
            if (hasVin()) {
                if (!getVin()
                        .equals(other.getVin())) {
                    return false;
                }
            }
            if (hasLongitude() != other.hasLongitude()) {
                return false;
            }
            if (hasLongitude()) {
                if (!getLongitude()
                        .equals(other.getLongitude())) {
                    return false;
                }
            }
            if (hasLatitude() != other.hasLatitude()) {
                return false;
            }
            if (hasLatitude()) {
                if (!getLatitude()
                        .equals(other.getLatitude())) {
                    return false;
                }
            }
            if (hasUtcTimestamp() != other.hasUtcTimestamp()) {
                return false;
            }
            if (hasUtcTimestamp()) {
                if (!getUtcTimestamp()
                        .equals(other.getUtcTimestamp())) {
                    return false;
                }
            }
            if (!unknownFields.equals(other.unknownFields)) {
                return false;
            }
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasVin()) {
                hash = (37 * hash) + VIN_FIELD_NUMBER;
                hash = (53 * hash) + getVin().hashCode();
            }
            if (hasLongitude()) {
                hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
                hash = (53 * hash) + getLongitude().hashCode();
            }
            if (hasLatitude()) {
                hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
                hash = (53 * hash) + getLatitude().hashCode();
            }
            if (hasUtcTimestamp()) {
                hash = (37 * hash) + UTCTIMESTAMP_FIELD_NUMBER;
                hash = (53 * hash) + getUtcTimestamp().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static others.MessageProtos.Data parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static others.MessageProtos.Data parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static others.MessageProtos.Data parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static others.MessageProtos.Data parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static others.MessageProtos.Data parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static others.MessageProtos.Data parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static others.MessageProtos.Data parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static others.MessageProtos.Data parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static others.MessageProtos.Data parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static others.MessageProtos.Data parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static others.MessageProtos.Data parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static others.MessageProtos.Data parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(others.MessageProtos.Data prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code com.webmiddle.circulocorp.protocol.Data}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:com.webmiddle.circulocorp.protocol.Data)
                others.MessageProtos.DataOrBuilder {

            public static final com.google.protobuf.Descriptors.Descriptor
                    getDescriptor() {
                return others.MessageProtos.internal_static_com_webmiddle_circulocorp_protocol_Data_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
                    internalGetFieldAccessorTable() {
                return others.MessageProtos.internal_static_com_webmiddle_circulocorp_protocol_Data_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(others.MessageProtos.Data.class, others.MessageProtos.Data.Builder.class);
            }

            // Construct using com.webmiddle.circulocorp.protocol.protos.MessageProtos.Data.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                vin_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                longitude_ = "";
                bitField0_ = (bitField0_ & ~0x00000002);
                latitude_ = "";
                bitField0_ = (bitField0_ & ~0x00000004);
                utcTimestamp_ = "";
                bitField0_ = (bitField0_ & ~0x00000008);
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
                    getDescriptorForType() {
                return others.MessageProtos.internal_static_com_webmiddle_circulocorp_protocol_Data_descriptor;
            }

            @java.lang.Override
            public others.MessageProtos.Data getDefaultInstanceForType() {
                return others.MessageProtos.Data.getDefaultInstance();
            }

            @java.lang.Override
            public others.MessageProtos.Data build() {
                others.MessageProtos.Data result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public others.MessageProtos.Data buildPartial() {
                others.MessageProtos.Data result = new others.MessageProtos.Data(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.vin_ = vin_;
                if (((from_bitField0_ & 0x00000002) != 0)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.longitude_ = longitude_;
                if (((from_bitField0_ & 0x00000004) != 0)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.latitude_ = latitude_;
                if (((from_bitField0_ & 0x00000008) != 0)) {
                    to_bitField0_ |= 0x00000008;
                }
                result.utcTimestamp_ = utcTimestamp_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof others.MessageProtos.Data) {
                    return mergeFrom((others.MessageProtos.Data) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(others.MessageProtos.Data other) {
                if (other == others.MessageProtos.Data.getDefaultInstance()) {
                    return this;
                }
                if (other.hasVin()) {
                    bitField0_ |= 0x00000001;
                    vin_ = other.vin_;
                    onChanged();
                }
                if (other.hasLongitude()) {
                    bitField0_ |= 0x00000002;
                    longitude_ = other.longitude_;
                    onChanged();
                }
                if (other.hasLatitude()) {
                    bitField0_ |= 0x00000004;
                    latitude_ = other.latitude_;
                    onChanged();
                }
                if (other.hasUtcTimestamp()) {
                    bitField0_ |= 0x00000008;
                    utcTimestamp_ = other.utcTimestamp_;
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                if (!hasLongitude()) {
                    return false;
                }
                if (!hasLatitude()) {
                    return false;
                }
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                others.MessageProtos.Data parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (others.MessageProtos.Data) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }
            private int bitField0_;

            private java.lang.Object vin_ = "";

            /**
             * <code>optional string vin = 1;</code>
             *
             * @return Whether the vin field is set.
             */
            public boolean hasVin() {
                return ((bitField0_ & 0x00000001) != 0);
            }

            /**
             * <code>optional string vin = 1;</code>
             *
             * @return The vin.
             */
            public java.lang.String getVin() {
                java.lang.Object ref = vin_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs
                            = (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        vin_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>optional string vin = 1;</code>
             *
             * @return The bytes for vin.
             */
            public com.google.protobuf.ByteString
                    getVinBytes() {
                java.lang.Object ref = vin_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b
                            = com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    vin_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string vin = 1;</code>
             *
             * @param value The vin to set.
             * @return This builder for chaining.
             */
            public Builder setVin(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                vin_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string vin = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearVin() {
                bitField0_ = (bitField0_ & ~0x00000001);
                vin_ = getDefaultInstance().getVin();
                onChanged();
                return this;
            }

            /**
             * <code>optional string vin = 1;</code>
             *
             * @param value The bytes for vin to set.
             * @return This builder for chaining.
             */
            public Builder setVinBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                vin_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object longitude_ = "";

            /**
             * <code>required string longitude = 2;</code>
             *
             * @return Whether the longitude field is set.
             */
            public boolean hasLongitude() {
                return ((bitField0_ & 0x00000002) != 0);
            }

            /**
             * <code>required string longitude = 2;</code>
             *
             * @return The longitude.
             */
            public java.lang.String getLongitude() {
                java.lang.Object ref = longitude_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs
                            = (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        longitude_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>required string longitude = 2;</code>
             *
             * @return The bytes for longitude.
             */
            public com.google.protobuf.ByteString
                    getLongitudeBytes() {
                java.lang.Object ref = longitude_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b
                            = com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    longitude_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>required string longitude = 2;</code>
             *
             * @param value The longitude to set.
             * @return This builder for chaining.
             */
            public Builder setLongitude(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                longitude_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string longitude = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearLongitude() {
                bitField0_ = (bitField0_ & ~0x00000002);
                longitude_ = getDefaultInstance().getLongitude();
                onChanged();
                return this;
            }

            /**
             * <code>required string longitude = 2;</code>
             *
             * @param value The bytes for longitude to set.
             * @return This builder for chaining.
             */
            public Builder setLongitudeBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                longitude_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object latitude_ = "";

            /**
             * <code>required string latitude = 3;</code>
             *
             * @return Whether the latitude field is set.
             */
            public boolean hasLatitude() {
                return ((bitField0_ & 0x00000004) != 0);
            }

            /**
             * <code>required string latitude = 3;</code>
             *
             * @return The latitude.
             */
            public java.lang.String getLatitude() {
                java.lang.Object ref = latitude_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs
                            = (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        latitude_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>required string latitude = 3;</code>
             *
             * @return The bytes for latitude.
             */
            public com.google.protobuf.ByteString
                    getLatitudeBytes() {
                java.lang.Object ref = latitude_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b
                            = com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    latitude_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>required string latitude = 3;</code>
             *
             * @param value The latitude to set.
             * @return This builder for chaining.
             */
            public Builder setLatitude(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                latitude_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string latitude = 3;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearLatitude() {
                bitField0_ = (bitField0_ & ~0x00000004);
                latitude_ = getDefaultInstance().getLatitude();
                onChanged();
                return this;
            }

            /**
             * <code>required string latitude = 3;</code>
             *
             * @param value The bytes for latitude to set.
             * @return This builder for chaining.
             */
            public Builder setLatitudeBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                latitude_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object utcTimestamp_ = "";

            /**
             * <code>optional string utcTimestamp = 4;</code>
             *
             * @return Whether the utcTimestamp field is set.
             */
            public boolean hasUtcTimestamp() {
                return ((bitField0_ & 0x00000008) != 0);
            }

            /**
             * <code>optional string utcTimestamp = 4;</code>
             *
             * @return The utcTimestamp.
             */
            public java.lang.String getUtcTimestamp() {
                java.lang.Object ref = utcTimestamp_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs
                            = (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        utcTimestamp_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>optional string utcTimestamp = 4;</code>
             *
             * @return The bytes for utcTimestamp.
             */
            public com.google.protobuf.ByteString
                    getUtcTimestampBytes() {
                java.lang.Object ref = utcTimestamp_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b
                            = com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    utcTimestamp_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string utcTimestamp = 4;</code>
             *
             * @param value The utcTimestamp to set.
             * @return This builder for chaining.
             */
            public Builder setUtcTimestamp(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000008;
                utcTimestamp_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string utcTimestamp = 4;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearUtcTimestamp() {
                bitField0_ = (bitField0_ & ~0x00000008);
                utcTimestamp_ = getDefaultInstance().getUtcTimestamp();
                onChanged();
                return this;
            }

            /**
             * <code>optional string utcTimestamp = 4;</code>
             *
             * @param value The bytes for utcTimestamp to set.
             * @return This builder for chaining.
             */
            public Builder setUtcTimestampBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000008;
                utcTimestamp_ = value;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }

            // @@protoc_insertion_point(builder_scope:com.webmiddle.circulocorp.protocol.Data)
        }

        // @@protoc_insertion_point(class_scope:com.webmiddle.circulocorp.protocol.Data)
        private static final others.MessageProtos.Data DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new others.MessageProtos.Data();
        }

        public static others.MessageProtos.Data getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        @java.lang.Deprecated
        public static final com.google.protobuf.Parser<Data> PARSER = new com.google.protobuf.AbstractParser<Data>() {
            @java.lang.Override
            public Data parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Data(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Data> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Data> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public others.MessageProtos.Data getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface MessageOrBuilder extends
            // @@protoc_insertion_point(interface_extends:com.webmiddle.circulocorp.protocol.Message)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>repeated .com.webmiddle.circulocorp.protocol.Data message = 1;</code>
         */
        java.util.List<others.MessageProtos.Data>
                getMessageList();

        /**
         * <code>repeated .com.webmiddle.circulocorp.protocol.Data message = 1;</code>
         */
        others.MessageProtos.Data getMessage(int index);

        /**
         * <code>repeated .com.webmiddle.circulocorp.protocol.Data message = 1;</code>
         */
        int getMessageCount();

        /**
         * <code>repeated .com.webmiddle.circulocorp.protocol.Data message = 1;</code>
         */
        java.util.List<? extends others.MessageProtos.DataOrBuilder>
                getMessageOrBuilderList();

        /**
         * <code>repeated .com.webmiddle.circulocorp.protocol.Data message = 1;</code>
         */
        others.MessageProtos.DataOrBuilder getMessageOrBuilder(
                int index);
    }

    /**
     * Protobuf type {@code com.webmiddle.circulocorp.protocol.Message}
     */
    public static final class Message extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:com.webmiddle.circulocorp.protocol.Message)
            MessageOrBuilder {

        private static final long serialVersionUID = 0L;
        // Use Message.newBuilder() to construct.

        private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private Message() {
            message_ = java.util.Collections.emptyList();
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new Message();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
                getUnknownFields() {
            return this.unknownFields;
        }

        private Message(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields
                    = com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                                message_ = new java.util.ArrayList<others.MessageProtos.Data>();
                                mutable_bitField0_ |= 0x00000001;
                            }
                            message_.add(input.readMessage(others.MessageProtos.Data.PARSER, extensionRegistry));
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000001) != 0)) {
                    message_ = java.util.Collections.unmodifiableList(message_);
                }
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
                getDescriptor() {
            return others.MessageProtos.internal_static_com_webmiddle_circulocorp_protocol_Message_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
                internalGetFieldAccessorTable() {
            return others.MessageProtos.internal_static_com_webmiddle_circulocorp_protocol_Message_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(others.MessageProtos.Message.class, others.MessageProtos.Message.Builder.class);
        }

        public static final int MESSAGE_FIELD_NUMBER = 1;
        private java.util.List<others.MessageProtos.Data> message_;

        /**
         * <code>repeated .com.webmiddle.circulocorp.protocol.Data message = 1;</code>
         */
        @java.lang.Override
        public java.util.List<others.MessageProtos.Data> getMessageList() {
            return message_;
        }

        /**
         * <code>repeated .com.webmiddle.circulocorp.protocol.Data message = 1;</code>
         */
        @java.lang.Override
        public java.util.List<? extends others.MessageProtos.DataOrBuilder>
                getMessageOrBuilderList() {
            return message_;
        }

        /**
         * <code>repeated .com.webmiddle.circulocorp.protocol.Data message = 1;</code>
         */
        @java.lang.Override
        public int getMessageCount() {
            return message_.size();
        }

        /**
         * <code>repeated .com.webmiddle.circulocorp.protocol.Data message = 1;</code>
         */
        @java.lang.Override
        public others.MessageProtos.Data getMessage(int index) {
            return message_.get(index);
        }

        /**
         * <code>repeated .com.webmiddle.circulocorp.protocol.Data message = 1;</code>
         */
        @java.lang.Override
        public others.MessageProtos.DataOrBuilder getMessageOrBuilder(
                int index) {
            return message_.get(index);
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) {
                return true;
            }
            if (isInitialized == 0) {
                return false;
            }

            for (int i = 0; i < getMessageCount(); i++) {
                if (!getMessage(i).isInitialized()) {
                    memoizedIsInitialized = 0;
                    return false;
                }
            }
            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            for (int i = 0; i < message_.size(); i++) {
                output.writeMessage(1, message_.get(i));
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) {
                return size;
            }

            size = 0;
            for (int i = 0; i < message_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(1, message_.get(i));
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof others.MessageProtos.Message)) {
                return super.equals(obj);
            }
            others.MessageProtos.Message other = (others.MessageProtos.Message) obj;

            if (!getMessageList()
                    .equals(other.getMessageList())) {
                return false;
            }
            if (!unknownFields.equals(other.unknownFields)) {
                return false;
            }
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (getMessageCount() > 0) {
                hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
                hash = (53 * hash) + getMessageList().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static others.MessageProtos.Message parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static others.MessageProtos.Message parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static others.MessageProtos.Message parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static others.MessageProtos.Message parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static others.MessageProtos.Message parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static others.MessageProtos.Message parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static others.MessageProtos.Message parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static others.MessageProtos.Message parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static others.MessageProtos.Message parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static others.MessageProtos.Message parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static others.MessageProtos.Message parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static others.MessageProtos.Message parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(others.MessageProtos.Message prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code com.webmiddle.circulocorp.protocol.Message}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:com.webmiddle.circulocorp.protocol.Message)
                others.MessageProtos.MessageOrBuilder {

            public static final com.google.protobuf.Descriptors.Descriptor
                    getDescriptor() {
                return others.MessageProtos.internal_static_com_webmiddle_circulocorp_protocol_Message_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
                    internalGetFieldAccessorTable() {
                return others.MessageProtos.internal_static_com_webmiddle_circulocorp_protocol_Message_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(others.MessageProtos.Message.class, others.MessageProtos.Message.Builder.class);
            }

            // Construct using com.webmiddle.circulocorp.protocol.protos.MessageProtos.Message.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
                    getMessageFieldBuilder();
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                if (messageBuilder_ == null) {
                    message_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000001);
                } else {
                    messageBuilder_.clear();
                }
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
                    getDescriptorForType() {
                return others.MessageProtos.internal_static_com_webmiddle_circulocorp_protocol_Message_descriptor;
            }

            @java.lang.Override
            public others.MessageProtos.Message getDefaultInstanceForType() {
                return others.MessageProtos.Message.getDefaultInstance();
            }

            @java.lang.Override
            public others.MessageProtos.Message build() {
                others.MessageProtos.Message result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public others.MessageProtos.Message buildPartial() {
                others.MessageProtos.Message result = new others.MessageProtos.Message(this);
                int from_bitField0_ = bitField0_;
                if (messageBuilder_ == null) {
                    if (((bitField0_ & 0x00000001) != 0)) {
                        message_ = java.util.Collections.unmodifiableList(message_);
                        bitField0_ = (bitField0_ & ~0x00000001);
                    }
                    result.message_ = message_;
                } else {
                    result.message_ = messageBuilder_.build();
                }
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof others.MessageProtos.Message) {
                    return mergeFrom((others.MessageProtos.Message) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(others.MessageProtos.Message other) {
                if (other == others.MessageProtos.Message.getDefaultInstance()) {
                    return this;
                }
                if (messageBuilder_ == null) {
                    if (!other.message_.isEmpty()) {
                        if (message_.isEmpty()) {
                            message_ = other.message_;
                            bitField0_ = (bitField0_ & ~0x00000001);
                        } else {
                            ensureMessageIsMutable();
                            message_.addAll(other.message_);
                        }
                        onChanged();
                    }
                } else {
                    if (!other.message_.isEmpty()) {
                        if (messageBuilder_.isEmpty()) {
                            messageBuilder_.dispose();
                            messageBuilder_ = null;
                            message_ = other.message_;
                            bitField0_ = (bitField0_ & ~0x00000001);
                            messageBuilder_
                                    = com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders
                                            ? getMessageFieldBuilder() : null;
                        } else {
                            messageBuilder_.addAllMessages(other.message_);
                        }
                    }
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                for (int i = 0; i < getMessageCount(); i++) {
                    if (!getMessage(i).isInitialized()) {
                        return false;
                    }
                }
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                others.MessageProtos.Message parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (others.MessageProtos.Message) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }
            private int bitField0_;

            private java.util.List<others.MessageProtos.Data> message_
                    = java.util.Collections.emptyList();

            private void ensureMessageIsMutable() {
                if (!((bitField0_ & 0x00000001) != 0)) {
                    message_ = new java.util.ArrayList<others.MessageProtos.Data>(message_);
                    bitField0_ |= 0x00000001;
                }
            }

            private com.google.protobuf.RepeatedFieldBuilderV3<
            others.MessageProtos.Data, others.MessageProtos.Data.Builder, others.MessageProtos.DataOrBuilder> messageBuilder_;

            /**
             * <code>repeated .com.webmiddle.circulocorp.protocol.Data message = 1;</code>
             */
            public java.util.List<others.MessageProtos.Data> getMessageList() {
                if (messageBuilder_ == null) {
                    return java.util.Collections.unmodifiableList(message_);
                } else {
                    return messageBuilder_.getMessageList();
                }
            }

            /**
             * <code>repeated .com.webmiddle.circulocorp.protocol.Data message = 1;</code>
             */
            public int getMessageCount() {
                if (messageBuilder_ == null) {
                    return message_.size();
                } else {
                    return messageBuilder_.getCount();
                }
            }

            /**
             * <code>repeated .com.webmiddle.circulocorp.protocol.Data message = 1;</code>
             */
            public others.MessageProtos.Data getMessage(int index) {
                if (messageBuilder_ == null) {
                    return message_.get(index);
                } else {
                    return messageBuilder_.getMessage(index);
                }
            }

            /**
             * <code>repeated .com.webmiddle.circulocorp.protocol.Data message = 1;</code>
             */
            public Builder setMessage(
                    int index, others.MessageProtos.Data value) {
                if (messageBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureMessageIsMutable();
                    message_.set(index, value);
                    onChanged();
                } else {
                    messageBuilder_.setMessage(index, value);
                }
                return this;
            }

            /**
             * <code>repeated .com.webmiddle.circulocorp.protocol.Data message = 1;</code>
             */
            public Builder setMessage(
                    int index, others.MessageProtos.Data.Builder builderForValue) {
                if (messageBuilder_ == null) {
                    ensureMessageIsMutable();
                    message_.set(index, builderForValue.build());
                    onChanged();
                } else {
                    messageBuilder_.setMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .com.webmiddle.circulocorp.protocol.Data message = 1;</code>
             */
            public Builder addMessage(others.MessageProtos.Data value) {
                if (messageBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureMessageIsMutable();
                    message_.add(value);
                    onChanged();
                } else {
                    messageBuilder_.addMessage(value);
                }
                return this;
            }

            /**
             * <code>repeated .com.webmiddle.circulocorp.protocol.Data message = 1;</code>
             */
            public Builder addMessage(
                    int index, others.MessageProtos.Data value) {
                if (messageBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureMessageIsMutable();
                    message_.add(index, value);
                    onChanged();
                } else {
                    messageBuilder_.addMessage(index, value);
                }
                return this;
            }

            /**
             * <code>repeated .com.webmiddle.circulocorp.protocol.Data message = 1;</code>
             */
            public Builder addMessage(
                    others.MessageProtos.Data.Builder builderForValue) {
                if (messageBuilder_ == null) {
                    ensureMessageIsMutable();
                    message_.add(builderForValue.build());
                    onChanged();
                } else {
                    messageBuilder_.addMessage(builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .com.webmiddle.circulocorp.protocol.Data message = 1;</code>
             */
            public Builder addMessage(
                    int index, others.MessageProtos.Data.Builder builderForValue) {
                if (messageBuilder_ == null) {
                    ensureMessageIsMutable();
                    message_.add(index, builderForValue.build());
                    onChanged();
                } else {
                    messageBuilder_.addMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .com.webmiddle.circulocorp.protocol.Data message = 1;</code>
             */
            public Builder addAllMessage(
                    java.lang.Iterable<? extends others.MessageProtos.Data> values) {
                if (messageBuilder_ == null) {
                    ensureMessageIsMutable();
                    com.google.protobuf.AbstractMessageLite.Builder.addAll(
                            values, message_);
                    onChanged();
                } else {
                    messageBuilder_.addAllMessages(values);
                }
                return this;
            }

            /**
             * <code>repeated .com.webmiddle.circulocorp.protocol.Data message = 1;</code>
             */
            public Builder clearMessage() {
                if (messageBuilder_ == null) {
                    message_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000001);
                    onChanged();
                } else {
                    messageBuilder_.clear();
                }
                return this;
            }

            /**
             * <code>repeated .com.webmiddle.circulocorp.protocol.Data message = 1;</code>
             */
            public Builder removeMessage(int index) {
                if (messageBuilder_ == null) {
                    ensureMessageIsMutable();
                    message_.remove(index);
                    onChanged();
                } else {
                    messageBuilder_.remove(index);
                }
                return this;
            }

            /**
             * <code>repeated .com.webmiddle.circulocorp.protocol.Data message = 1;</code>
             */
            public others.MessageProtos.Data.Builder getMessageBuilder(
                    int index) {
                return getMessageFieldBuilder().getBuilder(index);
            }

            /**
             * <code>repeated .com.webmiddle.circulocorp.protocol.Data message = 1;</code>
             */
            public others.MessageProtos.DataOrBuilder getMessageOrBuilder(
                    int index) {
                if (messageBuilder_ == null) {
                    return message_.get(index);
                } else {
                    return messageBuilder_.getMessageOrBuilder(index);
                }
            }

            /**
             * <code>repeated .com.webmiddle.circulocorp.protocol.Data message = 1;</code>
             */
            public java.util.List<? extends others.MessageProtos.DataOrBuilder>
                    getMessageOrBuilderList() {
                if (messageBuilder_ != null) {
                    return messageBuilder_.getMessageOrBuilderList();
                } else {
                    return java.util.Collections.unmodifiableList(message_);
                }
            }

            /**
             * <code>repeated .com.webmiddle.circulocorp.protocol.Data message = 1;</code>
             */
            public others.MessageProtos.Data.Builder addMessageBuilder() {
                return getMessageFieldBuilder().addBuilder(others.MessageProtos.Data.getDefaultInstance());
            }

            /**
             * <code>repeated .com.webmiddle.circulocorp.protocol.Data message = 1;</code>
             */
            public others.MessageProtos.Data.Builder addMessageBuilder(
                    int index) {
                return getMessageFieldBuilder().addBuilder(index, others.MessageProtos.Data.getDefaultInstance());
            }

            /**
             * <code>repeated .com.webmiddle.circulocorp.protocol.Data message = 1;</code>
             */
            public java.util.List<others.MessageProtos.Data.Builder>
                    getMessageBuilderList() {
                return getMessageFieldBuilder().getBuilderList();
            }

            private com.google.protobuf.RepeatedFieldBuilderV3<
            others.MessageProtos.Data, others.MessageProtos.Data.Builder, others.MessageProtos.DataOrBuilder>
                    getMessageFieldBuilder() {
                if (messageBuilder_ == null) {
                    messageBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                    others.MessageProtos.Data, others.MessageProtos.Data.Builder, others.MessageProtos.DataOrBuilder>(
                            message_,
                            ((bitField0_ & 0x00000001) != 0),
                            getParentForChildren(),
                            isClean());
                    message_ = null;
                }
                return messageBuilder_;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }

            // @@protoc_insertion_point(builder_scope:com.webmiddle.circulocorp.protocol.Message)
        }

        // @@protoc_insertion_point(class_scope:com.webmiddle.circulocorp.protocol.Message)
        private static final others.MessageProtos.Message DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new others.MessageProtos.Message();
        }

        public static others.MessageProtos.Message getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        @java.lang.Deprecated
        public static final com.google.protobuf.Parser<Message> PARSER = new com.google.protobuf.AbstractParser<Message>() {
            @java.lang.Override
            public Message parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Message(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Message> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Message> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public others.MessageProtos.Message getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor internal_static_com_webmiddle_circulocorp_protocol_Data_descriptor;
    private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_com_webmiddle_circulocorp_protocol_Data_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor internal_static_com_webmiddle_circulocorp_protocol_Message_descriptor;
    private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_com_webmiddle_circulocorp_protocol_Message_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
            getDescriptor() {
        return descriptor;
    }
    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

    static {
        java.lang.String[] descriptorData = {
            "\n\rMessage.proto\022\"com.webmiddle.circuloco"
            + "rp.protocol\"N\n\004Data\022\013\n\003vin\030\001 \001(\t\022\021\n\tlong"
            + "itude\030\002 \002(\t\022\020\n\010latitude\030\003 \002(\t\022\024\n\014utcTime"
            + "stamp\030\004 \001(\t\"D\n\007Message\0229\n\007message\030\001 \003(\0132"
            + "(.com.webmiddle.circulocorp.protocol.Dat"
            + "aB:\n)com.webmiddle.circulocorp.protocol."
            + "protosB\rMessageProtos"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{});
        internal_static_com_webmiddle_circulocorp_protocol_Data_descriptor
                = getDescriptor().getMessageTypes().get(0);
        internal_static_com_webmiddle_circulocorp_protocol_Data_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_com_webmiddle_circulocorp_protocol_Data_descriptor,
                new java.lang.String[]{"Vin", "Longitude", "Latitude", "UtcTimestamp",});
        internal_static_com_webmiddle_circulocorp_protocol_Message_descriptor
                = getDescriptor().getMessageTypes().get(1);
        internal_static_com_webmiddle_circulocorp_protocol_Message_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_com_webmiddle_circulocorp_protocol_Message_descriptor,
                new java.lang.String[]{"Message",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
