package com.webmiddle.circulocorp.protocol.enums;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TripSpeedSourceProto.proto
public final class TripSpeedSourceProto {

    private TripSpeedSourceProto() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    /**
     * <pre>
     * Speed is determined by
     * </pre>
     *
     * Protobuf enum {@code TripSpeedSource}
     */
    public enum TripSpeedSource
            implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <pre>
         * Not supported
         * </pre>
         *
         * <code>TRIP_SPEED_SOURCE_NOT_SUPPORTED = 0;</code>
         */
        TRIP_SPEED_SOURCE_NOT_SUPPORTED(0),
        /**
         * <pre>
         * Speed is determined by speed sensor
         * </pre>
         *
         * <code>TRIP_SPEED_SOURCE_SPEED_SENSOR = 1;</code>
         */
        TRIP_SPEED_SOURCE_SPEED_SENSOR(1),
        /**
         * <pre>
         * Speed is determined by GPS speed.
         * </pre>
         *
         * <code>TRIP_SPEED_SOURCE_GPS = 2;</code>
         */
        TRIP_SPEED_SOURCE_GPS(2),
        /**
         * <pre>
         * Speed is determined by CAN bus
         * </pre>
         *
         * <code>TRIP_SPEED_SOURCE_CANBUS = 4;</code>
         */
        TRIP_SPEED_SOURCE_CANBUS(4),;

        /**
         * <pre>
         * Not supported
         * </pre>
         *
         * <code>TRIP_SPEED_SOURCE_NOT_SUPPORTED = 0;</code>
         */
        public static final int TRIP_SPEED_SOURCE_NOT_SUPPORTED_VALUE = 0;
        /**
         * <pre>
         * Speed is determined by speed sensor
         * </pre>
         *
         * <code>TRIP_SPEED_SOURCE_SPEED_SENSOR = 1;</code>
         */
        public static final int TRIP_SPEED_SOURCE_SPEED_SENSOR_VALUE = 1;
        /**
         * <pre>
         * Speed is determined by GPS speed.
         * </pre>
         *
         * <code>TRIP_SPEED_SOURCE_GPS = 2;</code>
         */
        public static final int TRIP_SPEED_SOURCE_GPS_VALUE = 2;
        /**
         * <pre>
         * Speed is determined by CAN bus
         * </pre>
         *
         * <code>TRIP_SPEED_SOURCE_CANBUS = 4;</code>
         */
        public static final int TRIP_SPEED_SOURCE_CANBUS_VALUE = 4;

        public final int getNumber() {
            return value;
        }

        /**
         * @param value The numeric wire value of the corresponding enum entry.
         * @return The enum associated with the given numeric wire value.
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @java.lang.Deprecated
        public static TripSpeedSource valueOf(int value) {
            return forNumber(value);
        }

        /**
         * @param value The numeric wire value of the corresponding enum entry.
         * @return The enum associated with the given numeric wire value.
         */
        public static TripSpeedSource forNumber(int value) {
            switch (value) {
                case 0:
                    return TRIP_SPEED_SOURCE_NOT_SUPPORTED;
                case 1:
                    return TRIP_SPEED_SOURCE_SPEED_SENSOR;
                case 2:
                    return TRIP_SPEED_SOURCE_GPS;
                case 4:
                    return TRIP_SPEED_SOURCE_CANBUS;
                default:
                    return null;
            }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<TripSpeedSource>
                internalGetValueMap() {
            return internalValueMap;
        }
        private static final com.google.protobuf.Internal.EnumLiteMap<
        TripSpeedSource> internalValueMap
                = new com.google.protobuf.Internal.EnumLiteMap<TripSpeedSource>() {
            public TripSpeedSource findValueByNumber(int number) {
                return TripSpeedSource.forNumber(number);
            }
        };

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
                getValueDescriptor() {
            return getDescriptor().getValues().get(ordinal());
        }

        public final com.google.protobuf.Descriptors.EnumDescriptor
                getDescriptorForType() {
            return getDescriptor();
        }

        public static final com.google.protobuf.Descriptors.EnumDescriptor
                getDescriptor() {
            return TripSpeedSourceProto.getDescriptor().getEnumTypes().get(0);
        }

        private static final TripSpeedSource[] VALUES = values();

        public static TripSpeedSource valueOf(
                com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
            if (desc.getType() != getDescriptor()) {
                throw new java.lang.IllegalArgumentException(
                        "EnumValueDescriptor is not for this type.");
            }
            return VALUES[desc.getIndex()];
        }

        private final int value;

        private TripSpeedSource(int value) {
            this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:TripSpeedSource)
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
            getDescriptor() {
        return descriptor;
    }
    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

    static {
        java.lang.String[] descriptorData = {
            "\n\032TripSpeedSourceProto.proto*\223\001\n\017TripSpe"
            + "edSource\022#\n\037TRIP_SPEED_SOURCE_NOT_SUPPOR"
            + "TED\020\000\022\"\n\036TRIP_SPEED_SOURCE_SPEED_SENSOR\020"
            + "\001\022\031\n\025TRIP_SPEED_SOURCE_GPS\020\002\022\034\n\030TRIP_SPE"
            + "ED_SOURCE_CANBUS\020\004"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
